memsim: main.cpp memory.cpp hex.cpp memory.h hex.h 
	g++ -pedantic -Wall -Werror -Wextra -g -std=c++11 -c -o main.o main.cpp 
	g++ -pedantic -Wall -Werror -Wextra -g -std=c++11 -c -o memory.o memory.cpp
	g++ -pedantic -Wall -Werror -Wextra -g -std=c++11 -c -o hex.o hex.cpp
	g++ -pedantic -Wall -Werror -Wextra -g -std=c++11 -o memsim main.o memory.o hex.o
clean: 
	rm *.o